#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from ast.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "ast.y"

	#include<stdio.h>
	#include<stdlib.h>
	#include<string.h>
	FILE *yyin;
	extern int yylineno;
	struct treeNode
	{
		char name[20];
		struct treeNode* left;
		struct treeNode* right;
		char str1[100];
		char str2[100];
	};
	struct treeNode *createNode(char *, struct treeNode *, struct treeNode *, char *, char *);
	struct treeNode *head;
	struct treeNode *tempNode1;
	struct treeNode *tempNode2;
	
	char temptype[50];
	char temp[50];
	char buffer[50];
	char tempFunc[50];
	char tempparams[100];
	char extraval[20];
	char templog[20];
	char temprel[20];
	
	int closure = 0;
	int tempval;
	void display();
	int height(struct treeNode *);
	void printLevel(struct treeNode *, int);
	void yyerror(const char*);
	int yylex();

#line 38 "ast.y"
typedef union 
{
	char *str;
	int num;
	struct treeNode *node;
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	INT	258
#define	MAIN	259
#define	OB	260
#define	CB	261
#define	SO	262
#define	SC	263
#define	CLOSURE	264
#define	COLON	265
#define	HASH	266
#define	INCLUDE	267
#define	LIBRARY	268
#define	IF	269
#define	ELSE	270
#define	WHILE	271
#define	FOR	272
#define	CONT	273
#define	BRK	274
#define	RTRN	275
#define	SEMICOLON	276
#define	BINARYOR	277
#define	BINARYAND	278
#define	LT	279
#define	GT	280
#define	LTE	281
#define	GTE	282
#define	NE	283
#define	EQ	284
#define	VOID	285
#define	CHAR	286
#define	COMMA	287
#define	EQUAL	288
#define	SUBPREFIX	289
#define	ADD	290
#define	SUB	291
#define	MUL	292
#define	DIV	293
#define	ADDRIGHT	294
#define	SUBRIGHT	295
#define	MULRIGHT	296
#define	DIVRIGHT	297
#define	ADDPREFIX	298
#define	ID	299
#define	NUM	300


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int INT;
static const int MAIN;
static const int OB;
static const int CB;
static const int SO;
static const int SC;
static const int CLOSURE;
static const int COLON;
static const int HASH;
static const int INCLUDE;
static const int LIBRARY;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int FOR;
static const int CONT;
static const int BRK;
static const int RTRN;
static const int SEMICOLON;
static const int BINARYOR;
static const int BINARYAND;
static const int LT;
static const int GT;
static const int LTE;
static const int GTE;
static const int NE;
static const int EQ;
static const int VOID;
static const int CHAR;
static const int COMMA;
static const int EQUAL;
static const int SUBPREFIX;
static const int ADD;
static const int SUB;
static const int MUL;
static const int DIV;
static const int ADDRIGHT;
static const int SUBRIGHT;
static const int MULRIGHT;
static const int DIVRIGHT;
static const int ADDPREFIX;
static const int ID;
static const int NUM;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,INT=258
	,MAIN=259
	,OB=260
	,CB=261
	,SO=262
	,SC=263
	,CLOSURE=264
	,COLON=265
	,HASH=266
	,INCLUDE=267
	,LIBRARY=268
	,IF=269
	,ELSE=270
	,WHILE=271
	,FOR=272
	,CONT=273
	,BRK=274
	,RTRN=275
	,SEMICOLON=276
	,BINARYOR=277
	,BINARYAND=278
	,LT=279
	,GT=280
	,LTE=281
	,GTE=282
	,NE=283
	,EQ=284
	,VOID=285
	,CHAR=286
	,COMMA=287
	,EQUAL=288
	,SUBPREFIX=289
	,ADD=290
	,SUB=291
	,MUL=292
	,DIV=293
	,ADDRIGHT=294
	,SUBRIGHT=295
	,MULRIGHT=296
	,DIVRIGHT=297
	,ADDPREFIX=298
	,ID=299
	,NUM=300


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::INT=258;
const int YY_parse_CLASS::MAIN=259;
const int YY_parse_CLASS::OB=260;
const int YY_parse_CLASS::CB=261;
const int YY_parse_CLASS::SO=262;
const int YY_parse_CLASS::SC=263;
const int YY_parse_CLASS::CLOSURE=264;
const int YY_parse_CLASS::COLON=265;
const int YY_parse_CLASS::HASH=266;
const int YY_parse_CLASS::INCLUDE=267;
const int YY_parse_CLASS::LIBRARY=268;
const int YY_parse_CLASS::IF=269;
const int YY_parse_CLASS::ELSE=270;
const int YY_parse_CLASS::WHILE=271;
const int YY_parse_CLASS::FOR=272;
const int YY_parse_CLASS::CONT=273;
const int YY_parse_CLASS::BRK=274;
const int YY_parse_CLASS::RTRN=275;
const int YY_parse_CLASS::SEMICOLON=276;
const int YY_parse_CLASS::BINARYOR=277;
const int YY_parse_CLASS::BINARYAND=278;
const int YY_parse_CLASS::LT=279;
const int YY_parse_CLASS::GT=280;
const int YY_parse_CLASS::LTE=281;
const int YY_parse_CLASS::GTE=282;
const int YY_parse_CLASS::NE=283;
const int YY_parse_CLASS::EQ=284;
const int YY_parse_CLASS::VOID=285;
const int YY_parse_CLASS::CHAR=286;
const int YY_parse_CLASS::COMMA=287;
const int YY_parse_CLASS::EQUAL=288;
const int YY_parse_CLASS::SUBPREFIX=289;
const int YY_parse_CLASS::ADD=290;
const int YY_parse_CLASS::SUB=291;
const int YY_parse_CLASS::MUL=292;
const int YY_parse_CLASS::DIV=293;
const int YY_parse_CLASS::ADDRIGHT=294;
const int YY_parse_CLASS::SUBRIGHT=295;
const int YY_parse_CLASS::MULRIGHT=296;
const int YY_parse_CLASS::DIVRIGHT=297;
const int YY_parse_CLASS::ADDPREFIX=298;
const int YY_parse_CLASS::ID=299;
const int YY_parse_CLASS::NUM=300;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		184
#define	YYFLAG		-32768
#define	YYNTBASE	47

#define YYTRANSLATE(x) ((unsigned)(x) <= 300 ? yytranslate[x] : 79)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,    46,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29,    30,    31,    32,    33,    34,    35,
    36,    37,    38,    39,    40,    41,    42,    43,    44,    45
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     5,    13,    15,    19,    22,    25,    28,    30,    34,
    37,    43,    48,    53,    59,    62,    66,    68,    72,    76,
    79,    82,    85,    88,    91,    94,    97,    98,   104,   115,
   125,   132,   133,   142,   152,   157,   160,   164,   167,   175,
   181,   187,   192,   198,   206,   209,   212,   216,   218,   222,
   224,   226,   230,   234,   236,   238,   240,   242,   244,   246,
   248,   250,   252,   254,   256,   258,   262,   264,   268,   272,
   274,   278,   282,   284,   286,   288
};

static const short yyrhs[] = {    11,
    12,    13,    51,     0,     3,     4,     5,     6,    50,    59,
    46,     0,    44,     0,     7,    58,     8,     0,    54,    51,
     0,    57,    51,     0,    52,    51,     0,    48,     0,    74,
    75,    21,     0,    74,    53,     0,    49,    33,    71,    32,
    53,     0,    49,    33,    71,    21,     0,    55,     5,     6,
    21,     0,    55,     5,    56,     6,    21,     0,    74,    49,
     0,    56,    32,    74,     0,    74,     0,     9,    10,    54,
     0,    71,    21,    58,     0,    62,    58,     0,    64,    58,
     0,    65,    58,     0,    66,    58,     0,    63,    58,     0,
    50,    58,     0,     1,    21,     0,     0,    55,     5,     6,
    50,    59,     0,    55,     5,    61,     6,     7,    58,    60,
    58,     8,    59,     0,    55,     5,     6,     7,    58,    60,
    58,     8,    59,     0,    55,     5,    61,     6,    50,    59,
     0,     0,     9,    10,    55,     5,     6,     7,    58,     8,
     0,     9,    10,    55,     5,    61,     6,     7,    58,     8,
     0,    61,    32,    74,    49,     0,    74,    49,     0,    74,
    75,    21,     0,    74,    64,     0,    49,    33,    49,     5,
    75,     6,    21,     0,    49,     5,    75,     6,    21,     0,
    49,    33,    71,    32,    64,     0,    49,    33,    71,    21,
     0,    14,     5,    67,     6,    50,     0,    14,     5,    67,
     6,    50,    15,    50,     0,    18,    21,     0,    19,    21,
     0,    20,    71,    21,     0,    68,     0,    68,    72,    68,
     0,    69,     0,    70,     0,    71,    73,    76,     0,    71,
    72,    76,     0,    76,     0,    22,     0,    23,     0,    24,
     0,    25,     0,    26,     0,    27,     0,    28,     0,    29,
     0,     3,     0,    30,     0,    31,     0,    75,    32,    49,
     0,    49,     0,    76,    35,    77,     0,    76,    36,    77,
     0,    77,     0,    77,    37,    78,     0,    77,    38,    78,
     0,    78,     0,    44,     0,    45,     0,     5,    76,     6,
     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    57,    64,    66,    68,    70,    71,    72,    73,    75,    76,
    78,    81,    83,    93,   103,   105,   106,   108,   110,   111,
   112,   113,   114,   115,   116,   117,   118,   120,   123,   130,
   137,   142,   144,   149,   156,   158,   161,   162,   164,   166,
   169,   172,   174,   175,   180,   181,   182,   184,   185,   187,
   188,   190,   192,   194,   196,   197,   199,   200,   201,   202,
   203,   204,   206,   207,   208,   210,   211,   213,   214,   215,
   217,   218,   219,   221,   222,   223
};

static const char * const yytname[] = {   "$","error","$illegal.","INT","MAIN",
"OB","CB","SO","SC","CLOSURE","COLON","HASH","INCLUDE","LIBRARY","IF","ELSE",
"WHILE","FOR","CONT","BRK","RTRN","SEMICOLON","BINARYOR","BINARYAND","LT","GT",
"LTE","GTE","NE","EQ","VOID","CHAR","COMMA","EQUAL","SUBPREFIX","ADD","SUB",
"MUL","DIV","ADDRIGHT","SUBRIGHT","MULRIGHT","DIVRIGHT","ADDPREFIX","ID","NUM",
"'~'","PreProcessorDirectives","Main","Identifier","CompoundStmt","Global","GlobeDeclaration",
"GlobeAssignExpr","FunctionDefinition","FunctionName","ParamsType","ClosureFunctionDefinition",
"Stmt","Function","ClosureFunction","FunctionParams","Declaration","FunctionCall",
"AssignExpr","SelectionStmt","JumpStmt","cond","Expr","relExp","logExp","Extra",
"logOp","relOp","Type","VarList","E","T","F",""
};
#endif

static const short yyr1[] = {     0,
    47,    48,    49,    50,    51,    51,    51,    51,    52,    52,
    53,    53,    54,    54,    55,    56,    56,    57,    58,    58,
    58,    58,    58,    58,    58,    58,    58,    59,    59,    59,
    59,    59,    60,    60,    61,    61,    62,    62,    63,    63,
    64,    64,    65,    65,    66,    66,    66,    67,    67,    68,
    68,    69,    70,    71,    72,    72,    73,    73,    73,    73,
    73,    73,    74,    74,    74,    75,    75,    76,    76,    76,
    77,    77,    77,    78,    78,    78
};

static const short yyr2[] = {     0,
     4,     7,     1,     3,     2,     2,     2,     1,     3,     2,
     5,     4,     4,     5,     2,     3,     1,     3,     3,     2,
     2,     2,     2,     2,     2,     2,     0,     5,    10,     9,
     6,     0,     8,     9,     4,     2,     3,     2,     7,     5,
     5,     4,     5,     7,     2,     2,     3,     1,     3,     1,
     1,     3,     3,     1,     1,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     3,     1,     3,     3,     1,
     3,     3,     1,     1,     1,     3
};

static const short yydefact[] = {     0,
     0,     0,     0,    63,     0,    64,    65,     8,     1,     0,
     0,     0,     0,     0,     0,     0,     7,     5,     0,     6,
     3,    67,    10,     0,     0,    63,    18,     0,     0,     0,
    17,     0,     9,     0,     0,    15,    13,     0,     0,     0,
    74,    75,     0,    54,    70,    73,    66,     0,    32,    14,
    16,     0,    12,     0,     0,     0,     0,     0,     0,     0,
     0,     0,     0,    74,     0,     0,     0,     0,     0,     0,
     0,     0,     0,     0,     0,     0,    76,     0,    11,    68,
    69,    71,    72,    26,     0,    45,    46,     0,     0,     0,
    25,     4,    20,    24,    21,    22,    23,     0,    67,    38,
     0,     0,     2,     0,    48,    50,    51,     0,    47,    67,
     0,     0,     0,    19,     0,    37,     0,     0,     0,     0,
    55,    56,     0,    57,    58,    59,    60,    61,    62,     0,
     0,     0,     0,    42,     0,     0,    32,     0,     0,    36,
    43,    49,    53,    52,    40,     0,     0,    41,     0,    28,
     0,    32,     0,     0,     0,     0,     0,     0,    31,    35,
    44,    39,     0,     0,     0,     0,    32,     0,     0,    30,
    32,     0,     0,    29,     0,     0,     0,     0,    33,     0,
    34,     0,     0,     0
};

static const short yydefgoto[] = {   182,
     8,    65,    66,     9,    10,    23,    11,    12,    30,    13,
    67,    76,   157,   118,    68,    69,    70,    71,    72,   104,
   105,   106,   107,    73,   123,   131,    74,    24,    44,    45,
    46
};

static const short yypact[] = {    11,
     5,     7,    71,    21,    17,-32768,-32768,-32768,-32768,    71,
    71,    29,    71,     3,    70,   111,-32768,-32768,    60,-32768,
-32768,     6,-32768,    -9,    97,-32768,-32768,     3,    89,    54,
-32768,     9,-32768,     3,   126,-32768,-32768,   116,   111,     9,
-32768,-32768,   107,    43,    78,-32768,-32768,    37,   111,-32768,
-32768,    13,-32768,     3,     9,     9,     9,     9,   134,   142,
   144,   146,     9,    19,    38,   143,   145,   143,   143,   143,
   143,   143,   150,     3,   180,   140,-32768,   158,-32768,    78,
    78,-32768,-32768,-32768,     9,-32768,-32768,   171,     3,    28,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,   143,   160,-32768,
   122,    82,-32768,   188,   136,-32768,-32768,   153,-32768,-32768,
    77,   190,   124,-32768,     9,-32768,   189,    86,     3,   126,
-32768,-32768,     9,-32768,-32768,-32768,-32768,-32768,-32768,     9,
     9,   176,     3,-32768,     3,   143,   111,   191,   111,-32768,
   184,-32768,    43,    43,-32768,    92,   160,-32768,   121,-32768,
   143,   111,     3,   126,   179,   192,    37,   121,-32768,-32768,
-32768,-32768,   111,   193,    37,   198,   111,   196,   101,-32768,
   111,   199,    94,-32768,    37,   200,   197,    37,-32768,   201,
-32768,   208,   210,-32768
};

static const short yypgoto[] = {-32768,
-32768,   -13,   -33,   159,-32768,   157,   202,   -44,-32768,-32768,
   -40,  -102,    55,    45,-32768,-32768,   -65,-32768,-32768,-32768,
    93,-32768,-32768,   -26,   104,-32768,    -3,   -71,   -36,   128,
   132
};


#define	YYLAST		218


static const short yytable[] = {    14,
    22,    49,   101,    52,    75,    43,    14,    14,   100,    14,
   -15,    33,    28,    40,    36,    31,     2,   111,    77,     3,
    47,     1,    34,    -3,    15,    91,    16,    93,    94,    95,
    96,    97,    40,    19,   150,    51,    88,    59,    32,    26,
    78,    40,    89,    48,   -27,    28,    21,    55,    56,   159,
    60,    -3,    41,    42,    61,    62,    63,   114,   108,    38,
    99,   146,    26,   113,   170,    29,     6,     7,   174,   148,
    90,    64,    42,     4,    25,   110,   112,    55,    56,     5,
    64,    42,   132,   137,    26,    39,   141,   117,   113,     6,
     7,   138,    75,   143,   144,   149,   108,   155,   119,   176,
     6,     7,    35,    26,   152,   140,   172,    75,    34,    37,
   158,     6,     7,    26,    57,    58,   164,   139,   166,   110,
   161,   147,    75,    34,   168,   139,    75,    53,    92,   156,
     6,     7,    48,    28,   177,   153,    50,   180,    54,   160,
     6,     7,   116,    59,   134,    26,    85,    40,    28,    48,
   -27,   -27,    92,    34,    84,   135,    60,   121,   122,    28,
    61,    62,    63,    28,    86,   119,    87,    28,    17,    18,
    98,    20,     6,     7,   121,   122,   124,   125,   126,   127,
   128,   129,    80,    81,   102,   103,    64,    42,    82,    83,
    32,   109,   115,   120,   133,   136,   145,   151,   154,   162,
   167,   163,   169,   171,   179,   175,   178,   183,   181,   184,
    79,   130,   165,   173,     0,   142,     0,    27
};

static const short yycheck[] = {     3,
    14,    35,    74,    40,    49,    32,    10,    11,    74,    13,
     5,    21,    16,     5,    28,    19,    12,    89,     6,    13,
    34,    11,    32,     5,     4,    66,    10,    68,    69,    70,
    71,    72,     5,     5,   137,    39,    63,     1,    33,     3,
    54,     5,     5,     7,     8,    49,    44,    35,    36,   152,
    14,    33,    44,    45,    18,    19,    20,    98,    85,     6,
    74,   133,     3,    90,   167,     6,    30,    31,   171,   135,
    33,    44,    45,     3,     5,    89,    90,    35,    36,     9,
    44,    45,     6,   117,     3,    32,   120,     6,   115,    30,
    31,     6,   137,   130,   131,   136,   123,     6,   102,     6,
    30,    31,     6,     3,   138,   119,     6,   152,    32,    21,
   151,    30,    31,     3,    37,    38,   157,    32,   163,   133,
   154,   135,   167,    32,   165,    32,   171,    21,     8,     9,
    30,    31,     7,   137,   175,   139,    21,   178,    32,   153,
    30,    31,    21,     1,    21,     3,     5,     5,   152,     7,
     8,     9,     8,    32,    21,    32,    14,    22,    23,   163,
    18,    19,    20,   167,    21,   169,    21,   171,    10,    11,
    21,    13,    30,    31,    22,    23,    24,    25,    26,    27,
    28,    29,    55,    56,     5,    46,    44,    45,    57,    58,
    33,    21,    33,     6,     5,     7,    21,     7,    15,    21,
     8,    10,     5,     8,     8,     7,     7,     0,     8,     0,
    54,   108,   158,   169,    -1,   123,    -1,    16
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 58 "ast.y"
{ head = createNode("Start", NULL, yyvsp[0].node, "#include<stdio.h>", NULL);
							 printf("\n______________________________________________________\n"); 
							 printf("\nAST Successfully Created!!!\n\n"); 
							 display(); 
							 printf("\n______________________________________________________\n\n");;
    break;}
case 2:
#line 64 "ast.y"
{yyval.node = createNode("Main", yyvsp[-2].node, yyvsp[-1].node, NULL, NULL); ;
    break;}
case 3:
#line 66 "ast.y"
{strcpy(temp,yylval.str);;
    break;}
case 4:
#line 68 "ast.y"
{yyval.node = yyvsp[-1].node;;
    break;}
case 5:
#line 70 "ast.y"
{yyval.node = createNode("Global Sequence", yyvsp[-1].node, yyvsp[0].node, NULL, NULL);;
    break;}
case 6:
#line 71 "ast.y"
{yyval.node = createNode("Global Sequence", yyvsp[-1].node, yyvsp[0].node, NULL, NULL);;
    break;}
case 7:
#line 72 "ast.y"
{yyval.node = createNode("Global Sequence", yyvsp[-1].node, yyvsp[0].node, NULL, NULL);;
    break;}
case 8:
#line 73 "ast.y"
{yyval.node = yyvsp[0].node;;
    break;}
case 9:
#line 75 "ast.y"
{yyval.node = createNode("Declaration", NULL, yyvsp[-1].node, temptype, NULL); ;
    break;}
case 10:
#line 76 "ast.y"
{yyval.node = createNode("Declaration", NULL, yyvsp[0].node, temptype, NULL); ;
    break;}
case 11:
#line 78 "ast.y"
{ tempNode1 = createNode("=", NULL, NULL, temp, extraval);
								  yyval.node = createNode(",", tempNode1, yyvsp[0].node, NULL, NULL);
								  ;
    break;}
case 12:
#line 81 "ast.y"
{ yyval.node = createNode("=", NULL, NULL, temp, extraval);;
    break;}
case 13:
#line 84 "ast.y"
{	 if(closure)
		   	 	yyval.node = createNode("Closure Definition", NULL, NULL, tempFunc, "no params");
		   	 else
		   	 {	yyval.node = createNode("Function Definition", NULL, NULL, tempFunc, "no params");
			 strcpy(tempparams, "");
			 strcpy(tempFunc, "");
			 closure = 0;
		   	 }
		   ;
    break;}
case 14:
#line 94 "ast.y"
{	 if(closure)
		   	 	yyval.node = createNode("Closure Definition", NULL, NULL, tempFunc, tempparams);
		   	 else
		   	 	yyval.node = createNode("Function Definition", NULL, NULL, tempFunc, tempparams);
			 strcpy(tempparams, "");
			 strcpy(tempFunc, "");
			 closure = 0;
		   ;
    break;}
case 15:
#line 103 "ast.y"
{strcat(temptype, " "); strcat(temptype, temp); strcpy(tempFunc, temptype);;
    break;}
case 16:
#line 105 "ast.y"
{strcat(tempparams, temptype); strcat(tempparams, " ");;
    break;}
case 17:
#line 106 "ast.y"
{strcat(tempparams, temptype); strcat(tempparams, " ");;
    break;}
case 18:
#line 108 "ast.y"
{yyval.node = yyvsp[0].node;;
    break;}
case 19:
#line 110 "ast.y"
{yyval.node = createNode("Sequence", NULL, yyvsp[0].node, extraval, NULL); ;
    break;}
case 20:
#line 111 "ast.y"
{yyval.node = createNode("Sequence", yyvsp[-1].node, yyvsp[0].node, NULL, NULL); ;
    break;}
case 21:
#line 112 "ast.y"
{yyval.node = createNode("Sequence", yyvsp[-1].node, yyvsp[0].node, NULL, NULL); ;
    break;}
case 22:
#line 113 "ast.y"
{yyval.node = createNode("Sequence", yyvsp[-1].node, yyvsp[0].node, NULL, NULL); ;
    break;}
case 23:
#line 114 "ast.y"
{yyval.node = createNode("Sequence", yyvsp[-1].node, yyvsp[0].node, NULL, NULL); ;
    break;}
case 24:
#line 115 "ast.y"
{yyval.node = createNode("Sequence", yyvsp[-1].node, yyvsp[0].node, NULL, NULL); ;
    break;}
case 25:
#line 116 "ast.y"
{yyval.node = createNode("Sequence", yyvsp[-1].node, yyvsp[0].node, NULL, NULL); ;
    break;}
case 26:
#line 117 "ast.y"
{yyerrok; yyclearin; printf("missing ';'\n"); yyval.node = createNode("error", NULL, NULL, "semicolon missing", NULL);;
    break;}
case 27:
#line 118 "ast.y"
{printf("");;
    break;}
case 28:
#line 120 "ast.y"
{	tempNode1 = createNode(tempFunc, NULL, yyvsp[-1].node, "no params", NULL);
							yyval.node = createNode("Functions", tempNode1, yyvsp[0].node, NULL, NULL);
							strcpy(tempFunc,"");	;
    break;}
case 29:
#line 124 "ast.y"
{	tempNode2 = createNode("Function Sequence", yyvsp[-4].node, yyvsp[-2].node, NULL, NULL);
	   	tempNode1 = createNode(tempFunc, NULL, tempNode2, tempparams, NULL);
	   	strcpy(tempparams, "");
	   	strcpy(tempFunc,"");
	   	tempNode2 = createNode("Closure Sequence", yyvsp[-3].node, yyvsp[0].node, NULL, NULL);
		yyval.node = createNode("Functions", NULL, tempNode1, tempNode2, NULL);		;
    break;}
case 30:
#line 131 "ast.y"
{	tempNode2 = createNode("Function Sequence", yyvsp[-4].node, yyvsp[-2].node, NULL, NULL);
	   	tempNode1 = createNode(tempFunc, NULL, tempNode2, "no params", NULL);
	   	strcpy(tempparams, "");
	   	strcpy(tempFunc,"");
	   	tempNode2 = createNode("Closure Sequence", yyvsp[-3].node, yyvsp[0].node, NULL, NULL);
		yyval.node = createNode("Functions", NULL, tempNode1, tempNode2, NULL);		;
    break;}
case 31:
#line 138 "ast.y"
{	tempNode1 = createNode(tempFunc, NULL, yyvsp[-1].node, tempparams, NULL);
		yyval.node = createNode("Functions", tempNode1, yyvsp[0].node, NULL, NULL);
		strcpy(tempFunc,"");
		strcpy(tempparams,"");	;
    break;}
case 32:
#line 142 "ast.y"
{printf("");;
    break;}
case 33:
#line 145 "ast.y"
{	strcat(tempFunc, " closure");
		 	yyval.node = createNode(tempFunc, NULL, yyvsp[-1].node, "no params", NULL);
		 	strcpy(tempFunc, "");		
		 ;
    break;}
case 34:
#line 150 "ast.y"
{	strcat(tempFunc, " closure");
	        	yyval.node = createNode(tempFunc, NULL, yyvsp[-1].node, tempparams, NULL);
	        	strcpy(tempFunc, "");
	        	strcpy(tempparams, "");  
	        ;
    break;}
case 35:
#line 156 "ast.y"
{strcat(tempparams, temptype); strcat(tempparams, " ");
							 strcat(tempparams, temp); strcat(tempparams, ",");;
    break;}
case 36:
#line 158 "ast.y"
{strcat(tempparams, temptype); strcat(tempparams, " ");
							 strcat(tempparams, temp);;
    break;}
case 37:
#line 161 "ast.y"
{yyval.node = createNode("Declaration", NULL, yyvsp[-1].node, temptype, NULL); ;
    break;}
case 38:
#line 162 "ast.y"
{yyval.node = createNode("Declaration", NULL, yyvsp[0].node, temptype, NULL); ;
    break;}
case 39:
#line 165 "ast.y"
{yyval.node = createNode("call", NULL, yyvsp[-2].node, temp, NULL); ;
    break;}
case 40:
#line 167 "ast.y"
{yyval.node = createNode("call", NULL, yyvsp[-2].node, temp, NULL); ;
    break;}
case 41:
#line 169 "ast.y"
{ tempNode1 = createNode("=", NULL, NULL, temp, extraval);
								  yyval.node = createNode(",", tempNode1, yyvsp[0].node, NULL, NULL);
								  ;
    break;}
case 42:
#line 172 "ast.y"
{ yyval.node = createNode("=", NULL, NULL, temp, extraval); ;
    break;}
case 43:
#line 174 "ast.y"
{yyval.node = createNode("if", yyvsp[-2].node, yyvsp[0].node, NULL, NULL); ;
    break;}
case 44:
#line 175 "ast.y"
{
	      		tempNode1 = createNode("if", yyvsp[-4].node, yyvsp[-2].node, NULL, NULL);
	      		tempNode2 = createNode("else", yyvsp[0].node, NULL, NULL, NULL);
	      		yyval.node = createNode("selection", tempNode1, tempNode2, NULL, NULL); ;
    break;}
case 45:
#line 180 "ast.y"
{yyval.node = createNode("continue", NULL, NULL, NULL, NULL); ;
    break;}
case 46:
#line 181 "ast.y"
{yyval.node = createNode("break", NULL, NULL, NULL, NULL); ;
    break;}
case 47:
#line 182 "ast.y"
{yyval.node = createNode("return", NULL, NULL, extraval, NULL); ;
    break;}
case 48:
#line 184 "ast.y"
{yyval.node = createNode("cond", NULL, NULL, extraval, NULL); ;
    break;}
case 49:
#line 185 "ast.y"
{yyval.node = createNode(templog, yyvsp[-2].node, yyvsp[0].node, NULL, NULL); ;
    break;}
case 50:
#line 187 "ast.y"
{yyval.node = yyvsp[0].node;;
    break;}
case 51:
#line 188 "ast.y"
{yyval.node = yyvsp[0].node;;
    break;}
case 52:
#line 190 "ast.y"
{sprintf(buffer, "%d", yyvsp[0].num); yyval.node = createNode(temprel, NULL, NULL, extraval, buffer); ;
    break;}
case 53:
#line 192 "ast.y"
{sprintf(buffer, "%d", yyvsp[0].num); yyval.node = createNode(templog, NULL, NULL, extraval, buffer); ;
    break;}
case 54:
#line 194 "ast.y"
{sprintf(buffer, "%d", yyvsp[0].num); strcpy(extraval, buffer);;
    break;}
case 55:
#line 196 "ast.y"
{strcpy(templog, "||");;
    break;}
case 56:
#line 197 "ast.y"
{strcpy(templog, "&&");;
    break;}
case 57:
#line 199 "ast.y"
{strcpy(temprel, "<");;
    break;}
case 58:
#line 200 "ast.y"
{strcpy(temprel, ">");;
    break;}
case 59:
#line 201 "ast.y"
{strcpy(temprel, "<=");;
    break;}
case 60:
#line 202 "ast.y"
{strcpy(temprel, ">=");;
    break;}
case 61:
#line 203 "ast.y"
{strcpy(temprel, "!=");;
    break;}
case 62:
#line 204 "ast.y"
{strcpy(temprel, "==");;
    break;}
case 63:
#line 206 "ast.y"
{strcpy(temptype,"int");;
    break;}
case 64:
#line 207 "ast.y"
{strcpy(temptype,"void");;
    break;}
case 65:
#line 208 "ast.y"
{strcpy(temptype,"char");;
    break;}
case 66:
#line 210 "ast.y"
{yyval.node = createNode("varlist", yyvsp[-2].node, NULL, ",", temp); ;
    break;}
case 67:
#line 211 "ast.y"
{ yyval.node = createNode("varlist", NULL, NULL, temp, NULL); ;
    break;}
case 68:
#line 213 "ast.y"
{yyval.num = yyvsp[-2].num + yyvsp[0].num;;
    break;}
case 69:
#line 214 "ast.y"
{yyval.num = yyvsp[-2].num - yyvsp[0].num;;
    break;}
case 71:
#line 217 "ast.y"
{yyval.num = yyvsp[-2].num * yyvsp[0].num;;
    break;}
case 72:
#line 218 "ast.y"
{yyval.num = yyvsp[-2].num / yyvsp[0].num;;
    break;}
case 74:
#line 221 "ast.y"
{yyval.num = -1;;
    break;}
case 75:
#line 222 "ast.y"
{yyval.num = yyvsp[0].num;;
    break;}
case 76:
#line 223 "ast.y"
{yyval.num = yyvsp[-1].num;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 226 "ast.y"


void yyerror(const char *msg)
{
	fprintf(stderr, "WARNING : line %d : %s\n", yylineno, msg);
}

struct treeNode *createNode(char *n, struct treeNode *l, struct treeNode *r, char *s1, char *s2)
{
	struct treeNode *temp = (struct treeNode *)(malloc(sizeof(struct treeNode)));
	strcpy(temp -> name, n);
	temp -> left = l;
	temp -> right = r;
	if(s1 == NULL)
		strcpy(temp -> str1, "");
	else
		strcpy(temp -> str1, s1);
	if(s2 == NULL)
		strcpy(temp -> str2, "");
	else
		strcpy(temp -> str2, s2);
	return temp;
}

void display()
{
	struct treeNode *curr = head;
	int ht = height(curr);
	int i;
	for(i = 1; i <= ht; ++i)
	{
		for(int space = 15 - i + 1; space > 0; space--)
			printf("\t");
		printf("level : %d [", i);
		printLevel(curr, i);
		printf("]");
		printf("\n\n");
	}
}

int height(struct treeNode *curr)
{
	if(curr == NULL)
		return 0;
	else
	{
		int l = height(curr -> left);
		int r = height(curr -> right);
		if(l > r)
			return (l + 1);
		else
			return(r + 1);
	}
}

void printLevel(struct treeNode *curr, int level)
{
	if(curr == NULL)
		return;
	if(level == 1)
		printf("[ %s | %s | %s ]\t", curr -> name, curr -> str1, curr -> str2);
	else if(level > 1)
	{
		printLevel(curr -> left, level - 1);
		printLevel(curr -> right, level - 1);
		
	}
}

int main()
{
	head = (struct treeNode *)(malloc(sizeof(struct treeNode)));
	tempNode1 = (struct treeNode *)(malloc(sizeof(struct treeNode)));
	tempNode2 = (struct treeNode *)(malloc(sizeof(struct treeNode)));
	yyin = fopen("out.c", "r");
	if(!yyparse())
		;
	else
		printf("Invalid");
	fclose(yyin);
	return 0;
}


